algoritmo "Algoritmo 056"
// Função : Ler e somar varios numeros
// Autor : Yago Frankley
// Data : 09/06/2023
// Seção de Declarações 
   //c: contaodor
   //s: soma dos valores digitados
var
   c, s: inteiro
inicio
   escreval("Digite 1111 para sair")
   enquanto (c <> 1111) faca
      escreva("Digite um número: ")
      leia(c)
      s <- s + c
   fimenquanto
   escreval("A soma dos números digitados é:", s - 1111)
fimalgoritmo
