algoritmo "Algoritmo 007"
// Função : Ler um número e calcular o dobro e terça parte
// Autor : Yago Frankley
// Data : 14/04/2023
// Seção de Declarações 
   //n: numero digitado pelo usuario
   //d: dobro de n
   //t: terça parte de n
var
   n, d, t: real
inicio
   escreva("Digite um número: ")
   leia(n)
   d <- n * 2
   t <- n / 3
   escreval("O dobro de", n, " é ", d:1:1)
   escreva("A terça parte de", n, " é ", t:1:2)
fimalgoritmo
