algoritmo "Algoritmo 004"
// Função : Ler dois valores e somar
// Autor : Yago Frankley
// Data : 13/04/2023
// Seção de Declarações
   //v1: valor 1 digitado pelo usuario
   //v2: valor 2 digitado pelo usuario
   //s: soma dos valores digitados pelo usuario
var
   v1, v2, s: inteiro
inicio
   escreva("Digite um valor: ")
   leia(v1)
   escreva("Digite outro valor: ")
   leia(v2)
   s <- v1 + v2
   escreva("A soma entre", v1, " e", v2, " é igual a", s)
fimalgoritmo
