algoritmo "Algoritmo 086"
// Função : usar procedimentos
// Autor : Yago Frankley
// Data : 17/07/2023
// Seção de Declarações 
   //n: nome
   //i: idade
var

procedimento gerador(n:caractere; i:inteiro)
inicio
   escreval("----------------------------------------")
   escreval("Meu nome é: ", n, ", e tenho", i, " anos")
   escreval("----------------------------------------")
fimprocedimento

inicio
   gerador("Yago", 24)
   gerador("Andre", 12)
   gerador("Carlos", 89)
fimalgoritmo
