algoritmo "Algoritmo 007"
// Função : Ler um número e calcular o dobro e terça parte
// Autor : Yago Frankley
// Data : 14/04/2023
// Seção de Declarações 
var
   numero, dobro, terca: real
inicio
   escreva("Digite um número: ")
   leia(numero)
   dobro <- numero * 2
   terca <- numero / 3
   escreval("O dobro de", numero, " é ", dobro:1:1)
   escreva("A terça parte de", numero, " é ", terca:1:2)
fimalgoritmo
